# Generated by Django 4.1 on 2022-08-25 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blognew_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blognew',
            options={'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterModelOptions(
            name='newcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='blognew',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.newcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='blognew',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='blognew',
            name='upgrade_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='newcategory',
            name='category_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Категория'),
        ),
    ]
